language: c

addons:
  apt:
    packages:
      - libasound2:i386
      - libcairo2:i386
      - libz1:i386
      - libbz2-1.0:i386
      - libssl1.0.0:i386
      - libfreetype6:i386

install: 
  - wget -O - get.pharo.org/70+vm | bash
  - ./scripts/install-packages.sh
  - ./scripts/disable-deprecation-warning.sh 

before_script:
  - ./scripts/test-tokyodb.sh

script:
  - ./pharo atomicPharoInstaller.image test --no-xterm --fail-on-failure "AtomicClassInstaller-Tests" "Shift-ClassBuilder-Tests" "Slot-Tests" "Shift-Changes-Tests" "Shift-Changes-Ficus-Tests"
  - ./pharo shiftClassInstaller.image test --no-xterm "*"

